### ISSUE TITLE
Migration checklist: DETAIL VIEWS

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-workbench#709]
- [x] Attachment: Tested and works

1. Issue #708 but this is not related to migration as it already exists
2. **is_locked** field is not active in new rwapi, do we need it? Total of **19** attachments have **is_locked** set to **true**

- [x] Imageset: Tested and works

1. **fetchIsImagesetNumberInImageset** should be replaced with new method

- [x] Reference: Tested and works
- [x] Library: Tested and works
- [x] Journal: Tested and works
- [x] Keyword: Tested and works

1. Have to review related_keyword saving etc. What's the main use case?

- [x] Project: Tested and works
- [x] Locality: Tested and works
- [x] Drillcore: Tested and works
- [x] Drillcore box: Tested and works
- [x] Site:
- [x] Site groundwater:
- [x] Area:
- [x] Sample:
- [x] Sample series:
- [x] Preparation:

1. Taxon_list needs to be implemented

- [x] Analysis:
- [x] Analysis parameter:
- [x] Analysis method:
- [x] Dataset:
- [x] Doi:
- [x] Specimen:
- [x] Collection:
- [x] Taxon:
- [x] Rock:
- [x] Stratigraphy:
- [x] Selection:
- [x] Agent:
- [x] Storage:
- [x] Visit:
- [x] Loan:

1. Fill lists using selection needs to be implemented

- [x] Accession:
- [x] Deaccession:
- [x] Web news:
- [x] Web pages:

**Comment by enmust** [comment]
Most detail views work fine, problems are with related data and file additions etc.

**Comment by enmust** [comment]
Closing this as detail views are checked and working, some problems were made into separate issues
