### ISSUE TITLE
Migration checklist: SEARCH VIEWS

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-workbench#710]
Search views are working but have to do a more in depth check like search fields, lookuptypes, headers, selections etc.
- [x] Attachment:
- [x] Imageset: backend support needed
- [x] Reference:
- [x] Library: searching references duplicate issue
- [x] Journal:
- [x] Keyword:- backend support needed
- [x] Project:
- [x] Locality:
- [x] Drillcore:
- [x] Drillcore box:
- [x] Site:
- [x] Site groundwater:
- [x] Area:
- [x] Sample:
- [x] Sample series:
- [x] Preparation:
- [x] Analysis: review dataset field, some problems with lookuptypes
- [x] Analysis parameter: backend support needed
- [x] Analysis method: backend support needed
- [x] Dataset: backend support needed
- [x] Doi:
- [x] Specimen:
- [x] Collection: backend support needed
- [x] Taxon:
- [x] Rock: backend support needed
- [x] Stratigraphy: backend support needed
- [x] Selection:
- [x] Agent:
- [x] Storage:
- [x] Visit: backend support needed
- [x] Loan: backend support needed
- [x] Accession: backend support needed
- [x] Deaccession: backend support needed
- [x] Web news: backend support needed
- [x] Web pages: backend support needed
