### ISSUE TITLE
Bugs/Issues with changing over to the new rwapi

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/sarv-workbench#759]
With the switch to the new rwapi some of the views might not behave correctly. So each of the views should be tested to see if there are any problems. This issue provides an overview of the current state of the testing process and any known issues. 

### Known issues:

- [x] ID-card login does not work
- [x] geocollections/rwapi#95 _(breaks files list view)_
- [x] geocollections/rwapi#96 _(breaks samples list view)_
- [x] geocollections/rwapi#97 _(breaks preparation list view)_
- [x] geocollections/rwapi#98 _(breaks keywords in reference view)_
- [x] Project parent object field shows `[object Object]`
- [x] Sample series detail view does not update after adding related data
- [x] Adding more that two specimen photos at once logs the user out after saving (FIXED: does not actually log out, but routes to `\`. made it so that it routes to list view instead)
- [x] pdf files do not open
- [x] If valid token in localstorage, login view should automatically reroute to dashboard

### Testing progress: 

**_If you have tested something and it works as expected, please check the checkbox_**

- [x] Login
- [x] Dashboard
- [x] Settings
#### Files
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Image series
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
####  References
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data

#### Libraries
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Journals
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update

#### Keywords
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Projects
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Localities
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
  - [x] Stratigraphy tab tries to add to `locality_description` not `locality_stratigraphy`
  - [x] Stratigraphy tab uses `is_prefered` key when adding/updating. This does not exist in the model or database. Would the equivalent be the `current` field.

#### Areas
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Sites
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Hydrogeology
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Drillcores
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Drillcore boxes
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Samples
- [x] List view
- [x] Detail view
- [ ] Import
- [x] Create
- [x] Update
- [x] Update related data
#### Sample series
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Preparations
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [ ] Update related data
  - Taxa section does not work.
#### Analysis
- [x] List view
- [x] Detail view
- [ ] Import
- [x] Create
- [x] Update
- [x] Update related data
#### Analysis parameters
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update

#### Analysis methods
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update

#### Datasets
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### DOI
- [x] List view
- [x] Detail view
- [ ] Create
- [ ] Update
- [x] Update related data
- Need to check that Datacite works correctly
#### Specimens
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Collections
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update

#### Taxa
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [ ] Update related data
  - [x] related webpages cannot be added throws -> {"error":"Can't get list_language object, check the ID"}
  - [x] related names cannot be added throws -> {"error":[1364,"Field 'language' doesn't have a default value"]}
  - [ ] related subtaxa does not update after adding item, need to refresh page 
#### Rocks
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [ ] Update related data
  - [x] chemical compound related data cannot be added throws "Adding of rock_element objects not permitted"
  - [x] localities related data cannot be added throws "Adding of rock_locality objects not permitted"
  - [ ] related subclasses does not update after adding item, need to refresh page
#### Stratigraphy
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Catalog
  - [x] List view
#### Selection series
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Agents
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
#### Locations
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Visits
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update

#### Loans
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
- [x] Update related data
#### Accessions
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
#### Deaccessions
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
#### Web pages
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update
#### Web news
- [x] List view
- [x] Detail view
- [x] Create
- [x] Update

**NOTE:** If you spot a issue that has not been listed here or view that is not written down in the testing progress list, feel free to edit this issue or comment below.
